### ISSUE TITLE
Image file doesn't exist at source /home/sahildua2305/Downloads/sahildua.jpg

### ISSUE THREAD

**Issue by kevzettler** [sahildua2305/text-watermark#4]
```
Kevs-MBP:examples kev$ cd /examples/basic-add-watermark/
Kevs-MBP:basic-add-watermark kev$ npm start

> basic-add-watermark@1.0.0 start /Users/kev/code/text-watermark/examples/basic-add-watermark
> npm install ../../ && node .

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN basic-add-watermark@1.0.0 No repository field.
npm WARN basic-add-watermark@1.0.0 No license field.

+ text-watermark@1.0.1
added 1 package in 0.292s
Error: Text-Watermark::addWatermark : Image file doesn't exist at source /home/sahildua2305/Downloads/sahildua.jpg
    at /Users/kev/code/text-watermark/text-watermark.js:159:21
    at FSReqWrap.oncomplete (fs.js:152:21)
Kevs-MBP:basic-add-watermark kev$
```

**Comment by sahildua2305** [comment]
Hi @kevzettler, did you try replacing the image file address [here](https://github.com/sahildua2305/text-watermark/blob/master/examples/basic-add-watermark/add-watermark.js#L18) with your own local image?
